- name: Allow TCP traffic on port 8080
  ansible.posix.firewalld:
        port: 8080/tcp
        state: enabled
        permanent: true
        immediate: true

- name: Allow TCP traffic on port 80
  ansible.posix.firewalld:
        port: 80/tcp
        state: enabled
        permanent: true
        immediate: true