---

- name: Check System
  include_tasks: check.yaml
- name: update packages
  include_tasks: update.yml
- name: install docker
  include_tasks: docker.yml
- name: open ports
  include_tasks: firewall.yml
- name: copy files
  include_tasks: copy_files.yml
- name: deploy apps
  include_tasks: deploy.yml


      
      
